### ISSUE TITLE
After the parameter m of number of transmittersm in main.py in the source code is changed to 50, the program cannot run.

### ISSUE THREAD

**Issue by Allan-waker** [navid-naderi/StateAugmented_RRM_GNN#1]
Thank you very much for your open source code. I encountered a problem when reproducing your code and would like to ask you for advice. After the parameter m of number of transmittersm in main.py in the source code is changed to 50, the program cannot run. What is the reason? (m=20 can operate normally)
![屏幕截图 2023-11-19 114806](https://github.com/navid-naderi/StateAugmented_RRM_GNN/assets/64625837/514efc64-84eb-4d4d-8359-9318609d6c3c)

**Comment by navid-naderi** [comment]
Thanks for your interest in the work and the source code. The issue with higher values of $m$ is that the data generation portion of the code becomes a bottleneck; the code attempts to generate configurations satisfying the distance constraints [here](https://github.com/navid-naderi/StateAugmented_RRM_GNN/blob/c0540b5ae9f8b3bb98e39a96b7d219fa8eed02d5/channel.py#L6C1-L8C41), and these might become infeasible when the number of nodes gets large. I would suggest modifying these parameters (as well as [the entire area size](https://github.com/navid-naderi/StateAugmented_RRM_GNN/blob/c0540b5ae9f8b3bb98e39a96b7d219fa8eed02d5/main.py#L32C1-L35C31)) based on the final version of the paper (see Section V-B [here](https://arxiv.org/abs/2207.02242)), which should allow scaling to larger network configurations.
